const checkedType = require('./checkedType'),
    curry = require('./curry'),
    deepClone = require('./deepClone'),
    isInContainer = require('./isInContainer'),
    debounce = require('./debounce'),
    throttle = require('./throttle'),
    random = require('./random'),
    forEach = require('./forEach'),
    filter = require('./filter'),
    map = require('./map'),
    find = require('./find'),
    findRight = require('./findRight'),
    every = require('./every'),
    some = require('./some'),
    reduce = require('./reduce'),
    reduceRight = require('./reduceRight'),
    swapIndex = require('./swapIndex'),
    camelCase = require('./camelCase'),
    toUpper = require('./toUpper'),
    pull = require('./pull'),
    unique = require('./unique'),
    remove = require('./remove'),
    toCurrency = require('./toCurrency'),
    limitExec = require('./limitExec');




module.exports = {
    checkedType,
    curry,
    deepClone,
    isInContainer,
    debounce,
    throttle,
    random,
    forEach,
    filter,
    swapIndex,
    reduce,
    map,
    camelCase,
    toUpper,
    pull,
    unique,
    remove,
    find,
    findRight,
    every,
    some,
    reduceRight,
    toCurrency,
    limitExec,
};